services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - kokkoro
      - chatterbox
      - coqui
    environment:
      - KOKKORO_URL=http://kokkoro:8001
      - CHATTERBOX_URL=http://chatterbox:8002
      - COQUI_URL=http://coqui:8003

  kokkoro:
    build: ./engines/kokkoro
    ports:
      - "8001:8001"
    volumes:
      - ./outputs:/app/outputs

  chatterbox:
    build: ./engines/chatterbox
    ports:
      - "8002:8002"
    volumes:
      - ./outputs:/app/outputs

  coqui:
    build: ./engines/coqui
    ports:
      - "8003:8003"
    volumes:
      - ./outputs:/app/outputs
