FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY engines/kokkoro/requirements.txt .
RUN pip install --no-cache-dir torch torchvision torchaudio
RUN pip install --no-cache-dir -r requirements.txt

COPY engines/kokkoro/app.py .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]